#Database configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: adidas_app
    password: adidas_app
    initialization-mode: always
    url: jdbc:postgresql://localhost/adidas?currentSchema=adidas
  jpa:
    open-in-view: 'false'
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: 'false'
        format_sql: 'true'
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: 'false'