# HTTP Server
server:
  port: 8888

spring:
  # Spring Cloud Config Server Repository
  cloud:
    config:
      server:
        git:
          uri: https://github.com/csantos92/adidas-technical-challenge-config

  # Spring properties for profiles
  profiles:
   active: devv